services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tech-radar
      POSTGRES_USER: tech
      POSTGRES_PASSWORD: radar
    ports:
      - "5432:5432"
    volumes:
      - ./../data:/var/lib/postgresql/data
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always