spring:
  application:
    name: tech-radar

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tech-radar}
    username: ${DB_USERNAME:tech}
    password: ${DB_PASSWORD:radar}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_MIN_IDLE:5}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      pool-name: TechRadarHikariCP
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: ${JPA_BATCH_SIZE:50}
          fetch_size: ${JPA_FETCH_SIZE:50}
        order_inserts: true
        order_updates: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}
    default-schema: ${DB_SCHEMA:public}

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: ${COMPRESSION_ENABLED:true}
    mime-types: ${COMPRESSION_MIME_TYPES:application/json,application/xml,text/html,text/plain}
    min-response-size: ${COMPRESSION_MIN_SIZE:1024}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics,prometheus}
      base-path: ${MANAGEMENT_BASE_PATH:/actuator}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:always}
      show-components: ${HEALTH_COMPONENTS:always}
      group:
        tech-radar:
          include: ${HEALTH_GROUPS:database,application,memory,technologyData}
    metrics:
      enabled: ${METRICS_ENABLED:true}
    prometheus:
      enabled: ${PROMETHEUS_ENABLED:true}

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
    allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_HEADERS:*}
    max-age: ${CORS_MAX_AGE:3600}
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret}
      expiration: ${JWT_EXPIRATION:86400000}
  cache:
    ttl: ${CACHE_TTL:3600}
