# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tech-radar'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]  # This allows Prometheus to access your local machine

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
