services:
  # Backend API Service
  tech-radar-api:
    image: tech-radar:latest
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tech-radar
      - DB_USERNAME=tech
      - DB_PASSWORD=radar
      - SPRING_DATA_REDIS_HOST=redis-stack
      - SPRING_DATA_REDIS_PORT=6379
      - MANAGEMENT_ENDPOINTS=health,metrics,prometheus
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis-stack:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - tech-radar-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tech-radar
      POSTGRES_USER: tech
      POSTGRES_PASSWORD: radar
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tech -d tech-radar" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tech-radar-network

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ../data/redis:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tech-radar-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - tech-radar-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ../data/grafana:/var/lib/grafana
      - ../config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - tech-radar-network

networks:
  tech-radar-network:
    driver: bridge
